
const FEATURE_NVRAM_AIISP_ISO_DRC_T AIISP_ISO_DRC_%04d = {
        .statistics_reg00={.bits ={.AIISP_DRC_Statistics_Reg00=0}},     // LTM_MAP_LOG_EN
        .statistics_reg01={.bits ={.AIISP_DRC_Statistics_Reg01=0}},     // LTM_WGT_LOG_EN
        .statistics_reg02={.bits ={.AIISP_DRC_Statistics_Reg02=1}},     // LTM_NONTRAN_MAP_TYPE
        .statistics_reg03={.bits ={.AIISP_DRC_Statistics_Reg03=1}},     // LTM_TRAN_MAP_TYPE
        .statistics_reg04={.bits ={.AIISP_DRC_Statistics_Reg04=2}},     // LTM_TRAN_WGT_TYPE
        .statistics_reg05={.bits ={.AIISP_DRC_Statistics_Reg05=16}},    // LTM_TRAN_WGT
        .statistics_reg06={.bits ={.AIISP_DRC_Statistics_Reg06=4}},     // LTM_RANGE_SCL
        .statistics_reg07={.bits ={.AIISP_DRC_Statistics_Reg07=8}},     // LTM_GAIN_TH
        .statistics_reg08={.bits ={.AIISP_DRC_Statistics_Reg08=0}},
        .statistics_reg09={.bits ={.AIISP_DRC_Statistics_Reg09=0}},
        .statistics_reg10={.bits ={.AIISP_DRC_Statistics_Reg10=4095}},
        .statistics_reg11={.bits ={.AIISP_DRC_Statistics_Reg11=255}},
        .statistics_reg12={.bits ={.AIISP_DRC_Statistics_Reg12=0}},
        .statistics_reg13={.bits ={.AIISP_DRC_Statistics_Reg13=0}},
        .statistics_reg14={.bits ={.AIISP_DRC_Statistics_Reg14=0}},
        .statistics_reg15={.bits ={.AIISP_DRC_Statistics_Reg15=0}},
        .statistics_reg16={.bits ={.AIISP_DRC_Statistics_Reg16=0}},
        .statistics_reg17={.bits ={.AIISP_DRC_Statistics_Reg17=0}},
        .statistics_reg18={.bits ={.AIISP_DRC_Statistics_Reg18=0}},
        .statistics_reg19={.bits ={.AIISP_DRC_Statistics_Reg19=0}},
        .cal_reg00 ={.bits ={.AIISP_DRC_Cal_Reg00=4}},
        .cal_reg01 ={.bits ={.AIISP_DRC_Cal_Reg01=24}},
        .cal_reg02 ={.bits ={.AIISP_DRC_Cal_Reg02=0}},
        .cal_reg03 ={.bits ={.AIISP_DRC_Cal_Reg03=255}},
        .cal_reg04 ={.bits ={.AIISP_DRC_Cal_Reg04=255}},
        .cal_reg05 ={.bits ={.AIISP_DRC_Cal_Reg05=3}},
        .cal_reg06 ={.bits ={.AIISP_DRC_Cal_Reg06=23}},
        .cal_reg07 ={.bits ={.AIISP_DRC_Cal_Reg07=96}},
        .cal_reg08 ={.bits ={.AIISP_DRC_Cal_Reg08=8}},
        .cal_reg09 ={.bits ={.AIISP_DRC_Cal_Reg09=48}},
        .cal_reg10 ={.bits ={.AIISP_DRC_Cal_Reg10=4096}},
        .cal_reg11 ={.bits ={.AIISP_DRC_Cal_Reg11=0}},
        .cal_reg12 ={.bits ={.AIISP_DRC_Cal_Reg12=0}},
        .cal_reg13 ={.bits ={.AIISP_DRC_Cal_Reg13=0}},
        .cal_reg14 ={.bits ={.AIISP_DRC_Cal_Reg14=0}},
        .cal_reg15 ={.bits ={.AIISP_DRC_Cal_Reg15=4}},
        .cal_reg16 ={.bits ={.AIISP_DRC_Cal_Reg16=2}},
        .cal_reg17 ={.bits ={.AIISP_DRC_Cal_Reg17=20}},
        .cal_reg18 ={.bits ={.AIISP_DRC_Cal_Reg18=0}},
        .cal_reg19 ={.bits ={.AIISP_DRC_Cal_Reg19=0}},
        .cal_reg20 ={.bits ={.AIISP_DRC_Cal_Reg20=0}},
        .cal_reg21 ={.bits ={.AIISP_DRC_Cal_Reg21=1}},
        .cal_reg22 ={.bits ={.AIISP_DRC_Cal_Reg22=1}},
        .cal_reg23 ={.bits ={.AIISP_DRC_Cal_Reg23=8}},
        .cal_reg24 ={.bits ={.AIISP_DRC_Cal_Reg24=32}},
        .cal_reg25 ={.bits ={.AIISP_DRC_Cal_Reg25=16}},
        .cal_reg26 ={.bits ={.AIISP_DRC_Cal_Reg26=4096}},
        .cal_reg27 ={.bits ={.AIISP_DRC_Cal_Reg27=64}},
        .cal_reg28 ={.bits ={.AIISP_DRC_Cal_Reg28=4096}},
        .cal_reg29 ={.bits ={.AIISP_DRC_Cal_Reg29=64}},
        .cal_reg30 ={.bits ={.AIISP_DRC_Cal_Reg30=0}},
        .cal_reg31 ={.bits ={.AIISP_DRC_Cal_Reg31=0}},
        .cal_reg32 ={.bits ={.AIISP_DRC_Cal_Reg32=0}},
        .cal_reg33 ={.bits ={.AIISP_DRC_Cal_Reg33=0}},
        .cal_reg34 ={.bits ={.AIISP_DRC_Cal_Reg34=0}},
        .cal_reg35 ={.bits ={.AIISP_DRC_Cal_Reg35=0}},
        .cal_reg36 ={.bits ={.AIISP_DRC_Cal_Reg36=0}},
        .cal_reg37 ={.bits ={.AIISP_DRC_Cal_Reg37=0}},
        .cal_reg38 ={.bits ={.AIISP_DRC_Cal_Reg38=0}},
        .cal_reg39 ={.bits ={.AIISP_DRC_Cal_Reg39=0}},
        .cal_reg40 ={.bits ={.AIISP_DRC_Cal_Reg40=0}},
        .cal_reg41 ={.bits ={.AIISP_DRC_Cal_Reg41=0}},
};
