const FEATURE_NVRAM_AIISP_LV_Pre_T AIISP_LV_Pre_%04d = {
        .swme_enable={.bits ={.AIISP_SWME_Enable=0}},
        .swme_sse_enable={.bits ={.AIISP_SWME_SSE_Enable=0}},
        .swme_reg00={.bits ={.AIISP_SWME_Reg00=0}},
        .swme_reg01={.bits ={.AIISP_SWME_Reg01=0}},
        .swme_reg02={.bits ={.AIISP_SWME_Reg02=0}},
        .swme_reg03={.bits ={.AIISP_SWME_Reg03=0}},
        .swme_reg04={.bits ={.AIISP_SWME_Reg04=0}},
        .swme_reg05={.bits ={.AIISP_SWME_Reg05=0}},
        .swme_reg06={.bits ={.AIISP_SWME_Reg06=0}},
        .swme_reg07={.bits ={.AIISP_SWME_Reg07=0}},
        .swme_reg08={.bits ={.AIISP_SWME_Reg08=0}},
        .swme_reg09={.bits ={.AIISP_SWME_Reg09=0}},
        .swme_reg10={.bits ={.AIISP_SWME_Reg10=0}},
        .swme_reg11={.bits ={.AIISP_SWME_Reg11=0}},
        .swme_reg12={.bits ={.AIISP_SWME_Reg12=0}},
        .swme_reg13={.bits ={.AIISP_SWME_Reg13=0}},
        .swme_reg14={.bits ={.AIISP_SWME_Reg14=0}},
        .swme_reg15={.bits ={.AIISP_SWME_Reg15=0}},
        .iso_atms_pre_idx={.bits ={.AIISP_ISO_ATMs_Pre_Idx=17}},
        .iso_atms_apu_idx={.bits ={.AIISP_ISO_ATMs_APU_Idx=16}},
        .iso_atms_post_idx={.bits ={.AIISP_ISO_ATMs_Post_Idx=16}},
        .iso_jpeg_idx={.bits ={.AIISP_ISO_JPEG_Idx=16}},
        .se_facefallback_ratio={.bits ={.AIISP_SE_FaceFallBack_Ratio=10000}},
        .ne_facefallback_ratio={.bits ={.AIISP_NE_FaceFallBack_Ratio=10000}},
        .le_facefallback_ratio={.bits ={.AIISP_LE_FaceFallBack_Ratio=10000}},
};