
const FEATURE_NVRAM_AIISP_ISO_APU_Part2_T AIISP_ISO_APU_Part2_%04d = {
        .model     ={.bits ={.AIISP_APU_Part2_Model=0}},
        .chi_r     ={.bits ={.AIISP_APU_Part2_chi_R=500}},
        .chi_gr    ={.bits ={.AIISP_APU_Part2_chi_GR=500}},
        .chi_gb    ={.bits ={.AIISP_APU_Part2_chi_GB=500}},
        .chi_b     ={.bits ={.AIISP_APU_Part2_chi_B=500}},
        .std_r     ={.bits ={.AIISP_APU_Part2_std_R=5000}},
        .std_gr    ={.bits ={.AIISP_APU_Part2_std_GR=5000}},
        .std_gb    ={.bits ={.AIISP_APU_Part2_std_GB=5000}},
        .std_b     ={.bits ={.AIISP_APU_Part2_std_B=5000}},
        .blend_r   ={.bits ={.AIISP_APU_Part2_blend_R=1000000}},
        .blend_gr  ={.bits ={.AIISP_APU_Part2_blend_GR=1000000}},
        .blend_gb  ={.bits ={.AIISP_APU_Part2_blend_GB=1000000}},
        .blend_b   ={.bits ={.AIISP_APU_Part2_blend_B=1000000}},
        .lambda    ={.bits ={.AIISP_APU_Part2_Lambda=64}},
        .rsv00     ={.bits ={.AIISP_APU_Part2_RSV00=0}},
        .rsv01     ={.bits ={.AIISP_APU_Part2_RSV01=0}},
        .rsv02     ={.bits ={.AIISP_APU_Part2_RSV02=0}},
        .rsv03     ={.bits ={.AIISP_APU_Part2_RSV03=0}},
        .rsv04     ={.bits ={.AIISP_APU_Part2_RSV04=0}},
        .rsv05     ={.bits ={.AIISP_APU_Part2_RSV05=0}},
        .rsv06     ={.bits ={.AIISP_APU_Part2_RSV06=0}},
        .rsv07     ={.bits ={.AIISP_APU_Part2_RSV07=0}},
        .rsv08     ={.bits ={.AIISP_APU_Part2_RSV08=0}},
        .rsv09     ={.bits ={.AIISP_APU_Part2_RSV09=0}},
        .rsv10     ={.bits ={.AIISP_APU_Part2_RSV10=0}},
        .rsv11     ={.bits ={.AIISP_APU_Part2_RSV11=0}},
        .rsv12     ={.bits ={.AIISP_APU_Part2_RSV12=0}},
        .rsv13     ={.bits ={.AIISP_APU_Part2_RSV13=0}},
        .rsv14     ={.bits ={.AIISP_APU_Part2_RSV14=0}},
        .rsv15     ={.bits ={.AIISP_APU_Part2_RSV15=0}},
};
