const FEATURE_NVRAM_AIISP_EV_T AIISP_EV_%04d = {
        .sel_size  ={.bits ={.AIISP_EV_Sel_Size=3}},
        .sel_se_policy={.bits ={.AIISP_EV_Sel_SE_Policy=2}},
        .sel_le_policy={.bits ={.AIISP_EV_Sel_LE_Policy=1}},
        .sel_sse_policy={.bits ={.AIISP_EV_Sel_SSE_Policy=1}},
        .sel_seq0  ={.bits ={.AIISP_EV_Sel_Seq0=2}},
        .sel_seq1  ={.bits ={.AIISP_EV_Sel_Seq1=2}},
        .sel_seq2  ={.bits ={.AIISP_EV_Sel_Seq2=2}},
        .sel_seq3  ={.bits ={.AIISP_EV_Sel_Seq3=2}},
        .sel_seq4  ={.bits ={.AIISP_EV_Sel_Seq4=2}},
        .sel_seq5  ={.bits ={.AIISP_EV_Sel_Seq5=2}},
        .sel_seq6  ={.bits ={.AIISP_EV_Sel_Seq6=255}},
        .sel_seq7  ={.bits ={.AIISP_EV_Sel_Seq7=255}},
        .sel_bss   ={.bits ={.AIISP_EV_Sel_BSS=2}},
        .sel_table_se_lv00={.bits ={.AIISP_EV_Sel_Table_SE_LV00=7000}},
        .sel_table_se_lv01={.bits ={.AIISP_EV_Sel_Table_SE_LV01=8000}},
        .sel_table_se_lv02={.bits ={.AIISP_EV_Sel_Table_SE_LV02=9000}},
        .sel_table_se_lv03={.bits ={.AIISP_EV_Sel_Table_SE_LV03=9000}},
        .sel_table_se_lv04={.bits ={.AIISP_EV_Sel_Table_SE_LV04=9000}},
        .sel_table_se_lv05={.bits ={.AIISP_EV_Sel_Table_SE_LV05=9000}},
        .sel_table_se_lv06={.bits ={.AIISP_EV_Sel_Table_SE_LV06=9000}},
        .sel_table_se_lv07={.bits ={.AIISP_EV_Sel_Table_SE_LV07=9000}},
        .sel_table_se_lv08={.bits ={.AIISP_EV_Sel_Table_SE_LV08=9000}},
        .sel_table_se_lv09={.bits ={.AIISP_EV_Sel_Table_SE_LV09=9000}},
        .sel_table_se_lv10={.bits ={.AIISP_EV_Sel_Table_SE_LV10=9000}},
        .sel_table_se_lv11={.bits ={.AIISP_EV_Sel_Table_SE_LV11=9000}},
        .sel_table_le_lv00={.bits ={.AIISP_EV_Sel_Table_LE_LV00=13000}},
        .sel_table_le_lv01={.bits ={.AIISP_EV_Sel_Table_LE_LV01=12000}},
        .sel_table_le_lv02={.bits ={.AIISP_EV_Sel_Table_LE_LV02=11000}},
        .sel_table_le_lv03={.bits ={.AIISP_EV_Sel_Table_LE_LV03=11000}},
        .sel_table_le_lv04={.bits ={.AIISP_EV_Sel_Table_LE_LV04=11000}},
        .sel_table_le_lv05={.bits ={.AIISP_EV_Sel_Table_LE_LV05=11000}},
        .sel_table_le_lv06={.bits ={.AIISP_EV_Sel_Table_LE_LV06=11000}},
        .sel_table_le_lv07={.bits ={.AIISP_EV_Sel_Table_LE_LV07=11000}},
        .sel_table_le_lv08={.bits ={.AIISP_EV_Sel_Table_LE_LV08=11000}},
        .sel_table_le_lv09={.bits ={.AIISP_EV_Sel_Table_LE_LV09=11000}},
        .sel_table_le_lv10={.bits ={.AIISP_EV_Sel_Table_LE_LV10=11000}},
        .sel_table_le_lv11={.bits ={.AIISP_EV_Sel_Table_LE_LV11=11000}},
        .part1_start={.bits ={.AIISP_Part1_Start=0}},
        .part1_end ={.bits ={.AIISP_Part1_End=0}},
        .part2_start={.bits ={.AIISP_Part2_Start=0}},
        .part2_end ={.bits ={.AIISP_Part2_End=0}},
        .part3_start={.bits ={.AIISP_Part3_Start=0}},
        .part3_end ={.bits ={.AIISP_Part3_End=0}},
        .mstream_start={.bits ={.AIISP_MStream_Start=0}},
        .mstream_end={.bits ={.AIISP_MStream_End=0}},
        .fefm_rsz_ratio={.bits ={.AIISP_FEFM_RSZ_Ratio=3600}},
        .tonemappingstatus={.bits ={.AIISP_ToneMappingStatus=0}},
};