
const FEATURE_NVRAM_AIISP_ISO_APU_Part1_T AIISP_ISO_APU_Part1_%04d = {
        .model     ={.bits ={.AIISP_APU_Part1_Model=0}},
        .chi_r     ={.bits ={.AIISP_APU_Part1_chi_R=500}},
        .chi_gr    ={.bits ={.AIISP_APU_Part1_chi_GR=500}},
        .chi_gb    ={.bits ={.AIISP_APU_Part1_chi_GB=500}},
        .chi_b     ={.bits ={.AIISP_APU_Part1_chi_B=500}},
        .std_r     ={.bits ={.AIISP_APU_Part1_std_R=5000}},
        .std_gr    ={.bits ={.AIISP_APU_Part1_std_GR=5000}},
        .std_gb    ={.bits ={.AIISP_APU_Part1_std_GB=5000}},
        .std_b     ={.bits ={.AIISP_APU_Part1_std_B=5000}},
        .blend_r   ={.bits ={.AIISP_APU_Part1_blend_R=1000000}},
        .blend_gr  ={.bits ={.AIISP_APU_Part1_blend_GR=1000000}},
        .blend_gb  ={.bits ={.AIISP_APU_Part1_blend_GB=1000000}},
        .blend_b   ={.bits ={.AIISP_APU_Part1_blend_B=1000000}},
        .lambda    ={.bits ={.AIISP_APU_Part1_Lambda=64}},
        .rsv00     ={.bits ={.AIISP_APU_Part1_RSV00=0}},
        .rsv01     ={.bits ={.AIISP_APU_Part1_RSV01=0}},
        .rsv02     ={.bits ={.AIISP_APU_Part1_RSV02=0}},
        .rsv03     ={.bits ={.AIISP_APU_Part1_RSV03=0}},
        .rsv04     ={.bits ={.AIISP_APU_Part1_RSV04=0}},
        .rsv05     ={.bits ={.AIISP_APU_Part1_RSV05=0}},
        .rsv06     ={.bits ={.AIISP_APU_Part1_RSV06=0}},
        .rsv07     ={.bits ={.AIISP_APU_Part1_RSV07=0}},
        .rsv08     ={.bits ={.AIISP_APU_Part1_RSV08=1}},
        .rsv09     ={.bits ={.AIISP_APU_Part1_RSV09=0}},
        .rsv10     ={.bits ={.AIISP_APU_Part1_RSV10=0}},
        .rsv11     ={.bits ={.AIISP_APU_Part1_RSV11=0}},
        .rsv12     ={.bits ={.AIISP_APU_Part1_RSV12=0}},
        .rsv13     ={.bits ={.AIISP_APU_Part1_RSV13=0}},
        .rsv14     ={.bits ={.AIISP_APU_Part1_RSV14=0}},
        .rsv15     ={.bits ={.AIISP_APU_Part1_RSV15=0}},
};
