const NVRAM_CAMERA_FEATURE_MSNR_STRUCT MSNR_%04d = {
    .CON={.MS_SCALES=7},
    .MS0={.MS_YNR_Y_STD=16,.MS_YNR_Y_BLD=16, .MS_YNR_Y_CEN=1, .MS_YNR_C_STD=16,.MS_YNR_C_BLD=48, .MS_YNR_C_L_DIFF=16},
    .MS1={.MS_YNR_Y_STD=8, .MS_YNR_Y_BLD=16, .MS_YNR_Y_CEN=0, .MS_YNR_C_STD=8, .MS_YNR_C_BLD=48, .MS_YNR_C_L_DIFF=8},
    .MS2={.MS_YNR_Y_STD=4, .MS_YNR_Y_BLD=16, .MS_YNR_Y_CEN=0, .MS_YNR_C_STD=4, .MS_YNR_C_BLD=48, .MS_YNR_C_L_DIFF=4},
    .MS3={.MS_YNR_Y_STD=2, .MS_YNR_Y_BLD=16, .MS_YNR_Y_CEN=0, .MS_YNR_C_STD=2, .MS_YNR_C_BLD=48, .MS_YNR_C_L_DIFF=2},
    .MS4={.MS_YNR_Y_STD=1, .MS_YNR_Y_BLD=16, .MS_YNR_Y_CEN=0, .MS_YNR_C_STD=1, .MS_YNR_C_BLD=48, .MS_YNR_C_L_DIFF=1},
    .MS5={.MS_YNR_Y_STD=0, .MS_YNR_Y_BLD=16, .MS_YNR_Y_CEN=0, .MS_YNR_C_STD=0, .MS_YNR_C_BLD=48, .MS_YNR_C_L_DIFF=0},
    .MS6={.MS_YNR_Y_STD=0, .MS_YNR_Y_BLD=16, .MS_YNR_Y_CEN=0, .MS_YNR_C_STD=0, .MS_YNR_C_BLD=48, .MS_YNR_C_L_DIFF=0},
};
