const ISP_NVRAM_OMC_T OMC_%04d = {
    .top       ={.bits ={.OMC_OMC_DISABLE=0, .OMC_OMC_BYPASS_ITP=0, .OMC_OMC_BYPASS_OVL=0, .OMC_OMC_BICUB_TYPE=1, .OMC_OMC_FMT_BIT=10, .OMC_OMC_OUT_UV_SWAP=0, .OMC_OMC_CRC_CLEAR=0, .OMC_OMC_SW_RST=0, .rsv_15=0}},
};