const FEATURE_NVRAM_SW_MSF_T SW_MSF_%04d = {
        .info      ={.bits ={.MSF_ISO=200, .MFB_D1A_MSF_FRAME_TOTAL=6, .MFB_D1A_MSF_SCALE_TOTAL=7, .MFB_D1A_MSF_FUS_MODE=0, .rsv_25=0}},
        .func      ={.bits ={.MSF_GF_EN=1, .MSF_DS_EN=1, .MSF_CM_EN=1, .MSF_LC_EN=1, .MSF_SL_EN=1, .MSF_AB_EN=1, .MSF_BC_EN=1, .MSF_BP_EN=0, .MSF_VB_EN=1, .MSF_RA_EN=1, .MSF_NLM_EN=1, .MSF_NES_EN=1, .MSF_HFE_EN=0, .rsv_13=0}},
        .ms1       ={.bits ={.MSF_MS_ROLL_SCALE=5, .MSF_MS_ROLL_RATIO0=0, .rsv_18=0}},
        .ms2       ={.bits ={.MSF_MS_ROLL_RATIO1=2048, .MSF_MS_ROLL_RATIO2=1024, .rsv_30=0}},
        .ms3       ={.bits ={.MSF_MS_ROLL_RATIO3=512, .MSF_MS_ROLL_RATIO4=381, .rsv_30=0}},
        .ms4       ={.bits ={.MSF_MS_ROLL_RATIO5=256, .MFB_D1A_MSF_MS_ALPHA_PRECISION=32, .rsv_21=0}},
        .fd1       ={.bits ={.MSF_FD_DEGRA_RATE=8, .MFB_D1A_MSF_FD_LFA_MODE=1, .MFB_D1A_MSF_FD_NES_EN=0, .MFB_D1A_MSF_FD_NES_RATE=16, .MFB_D1A_MSF_FD_FILTER_KERNEL_C0=16, .rsv_26=0}},
        .fd2       ={.bits ={.MFB_D1A_MSF_FD_FILTER_KERNEL_C1=16, .MFB_D1A_MSF_FD_FILTER_KERNEL_C2=16, .MFB_D1A_MSF_FD_FILTER_KERNEL_C3=119, .MFB_D1A_MSF_FD_FILTER_KERNEL_C4=119, .rsv_28=0}},
        .fd3       ={.bits ={.MFB_D1A_MSF_FD_FILTER_KERNEL_C5=119, .MFB_D1A_MSF_FD_FILTER_NORMALIZE_INV=72, .MSF_MSF_FD_SLOPE0=4, .MSF_FD_SLOPE1=8, .rsv_28=0}},
        .fd4       ={.bits ={.MSF_FD_SLOPE2=16, .MSF_FD_SLOPE3=16, .MSF_FD_SLOPE4=16, .MSF_FD_SLOPE5=16, .MSF_MSF_FD_INTERCEPT0=10}},
        .fd5       ={.bits ={.MSF_FD_INTERCEPT1=6, .MSF_FD_INTERCEPT2=4, .MSF_FD_INTERCEPT3=2, .MSF_FD_INTERCEPT4=1}},
        .fd6       ={.bits ={.MSF_FD_INTERCEPT5=0, .MSF_MSF_FD_NES_MAX0=2, .MSF_FD_NES_MAX1=1, .rsv_28=0}},
        .fd7       ={.bits ={.MSF_FD_NES_MAX2=1, .MSF_FD_NES_MAX3=0, .MSF_FD_NES_MAX4=0, .rsv_30=0}},
        .fd8       ={.bits ={.MSF_FD_NES_MAX5=0, .rsv_10=0}},
        .gd1       ={.bits ={.MSF_MSF_GD_SLOPE0=2, .MSF_GD_SLOPE1=4, .MSF_GD_SLOPE2=8, .MSF_GD_SLOPE3=12, .MSF_GD_SLOPE4=16, .rsv_30=0}},
        .gd2       ={.bits ={.MSF_GD_SLOPE5=20, .MSF_MSF_GD_INTERCEPT0=120, .MSF_GD_INTERCEPT1=80, .MSF_GD_INTERCEPT2=70, .rsv_30=0}},
        .gd3       ={.bits ={.MSF_GD_INTERCEPT3=65, .MSF_GD_INTERCEPT4=40, .MSF_GD_INTERCEPT5=25, .MSF_MSF_GD_FILTER_STD0=91}},
        .gd4       ={.bits ={.MSF_GD_FILTER_STD1=91, .MSF_GD_FILTER_STD2=91, .MSF_GD_FILTER_STD3=91, .MSF_GD_FILTER_STD4=91}},
        .gd5       ={.bits ={.MSF_GD_FILTER_STD5=91, .MSF_MSF_GD_NES_MAX0=30, .MSF_GD_NES_MAX1=20, .rsv_28=0}},
        .gd6       ={.bits ={.MSF_GD_NES_MAX2=17, .MSF_GD_NES_MAX3=16, .MSF_GD_NES_MAX4=10, .rsv_30=0}},
        .gd7       ={.bits ={.MSF_GD_NES_MAX5=6, .MSF_GD_UV_RATE=48, .MSF_GD_DEGRA_RATE=16, .MFB_D1A_MSF_GD_NES_EN=0, .rsv_23=0}},
        .gd8       ={.bits ={.MFB_D1A_MSF_GD_NES_RATE=64, .rsv_12=0}},
        .md1       ={.bits ={.MFB_D1A_MSF_MD_NES_EN=0, .MFB_D1A_MSF_MD_NES_RATE=16, .MSF_MSF_MD_SLOPE0=8, .MSF_MD_SLOPE1=16, .MSF_MD_SLOPE2=32, .rsv_31=0}},
        .md2       ={.bits ={.MSF_MD_SLOPE3=63, .MSF_MD_SLOPE4=63, .MSF_MD_SLOPE5=63, .MSF_MSF_MD_INTERCEPT0=17, .rsv_26=0}},
        .md3       ={.bits ={.MSF_MD_INTERCEPT1=13, .MSF_MD_INTERCEPT2=8, .MSF_MD_INTERCEPT3=6, .MSF_MD_INTERCEPT4=3}},
        .md4       ={.bits ={.MSF_MD_INTERCEPT5=2, .MSF_MSF_MD_FILTER_STD0=11, .MSF_MD_FILTER_STD1=11, .MSF_MD_FILTER_STD2=11, .MSF_MD_FILTER_STD3=11, .rsv_28=0}},
        .md5       ={.bits ={.MSF_MD_FILTER_STD4=11, .MSF_MD_FILTER_STD5=11, .MSF_MSF_MD_NES_MAX0=4, .MSF_MD_NES_MAX1=3, .rsv_30=0}},
        .md6       ={.bits ={.MSF_MD_NES_MAX2=2, .MSF_MD_NES_MAX3=1, .MSF_MD_NES_MAX4=0, .rsv_30=0}},
        .md7       ={.bits ={.MSF_MD_DEGRA_RATE=16, .MSF_MD_UV_RATE=16, .MSF_MD_NES_MAX5=0, .MSF_XD_THD0=48, .rsv_30=0}},
        .md8       ={.bits ={.MSF_XD_THD1=80, .MFB_D1A_MSF_XD_MODE=1, .rsv_9=0}},
        .rd1       ={.bits ={.MSF_MSF_RD_LIMIT_RATE0=128, .MSF_RD_LIMIT_RATE1=128, .MSF_RD_LIMIT_RATE2=128, .rsv_30=0}},
        .rd2       ={.bits ={.MSF_RD_LIMIT_RATE3=128, .MSF_RD_LIMIT_RATE4=128, .MSF_RD_LIMIT_RATE5=128, .rsv_30=0}},
        .rd3       ={.bits ={.MSF_MSF_RD_INTERCEPT0=30, .MSF_RD_INTERCEPT1=22, .MSF_RD_INTERCEPT2=15, .MSF_RD_INTERCEPT3=10}},
        .rd4       ={.bits ={.MSF_RD_INTERCEPT4=6, .MSF_RD_INTERCEPT5=4, .MSF_MSF_RD_STD_Y0=23, .MSF_RD_STD_Y1=23}},
        .rd5       ={.bits ={.MSF_RD_STD_Y2=23, .MSF_RD_STD_Y3=23, .MSF_RD_STD_Y4=23, .MSF_RD_STD_Y5=23}},
        .rd6       ={.bits ={.MSF_MSF_RD_STD_UV0=16, .MSF_RD_STD_UV1=16, .MSF_RD_STD_UV2=16, .MSF_RD_STD_UV3=16}},
        .rd7       ={.bits ={.MSF_RD_STD_UV4=16, .MSF_RD_STD_UV5=16, .MSF_RD_DEGRA_RATE=16, .MSF_RD_UV_RATE=16, .rsv_28=0}},
        .gf1       ={.bits ={.MSF_GF_LUMA_THD0=64, .MSF_GF_LUMA_THD1=128, .MSF_GF_EXPN=1, .MSF_GF_EXP_MAX=20}},
        .gf2       ={.bits ={.MSF_GF_EXP_MIN=1, .MSF_GF_EXP_MIN_SLOPE=40, .MSF_GF_THD_RATE_MIN=51, .rsv_26=0}},
        .gf3       ={.bits ={.MSF_GF_ALP_RATE_MIN=64, .MSF_GF_COEF_A0=2, .MSF_GF_COEF_A1=252, .MSF_GF_COEF_A2=4}},
        .gf4       ={.bits ={.MSF_GF_COEF_A3=252, .MSF_GF_COEF_A4=2, .MSF_GF_COEF_B0=0, .MSF_GF_COEF_B1=252}},
        .gf5       ={.bits ={.MSF_GF_COEF_B2=8, .MSF_GF_COEF_B3=252, .MSF_GF_COEF_B4=0, .MSF_GF_COEF_C0=252}},
        .gf6       ={.bits ={.MSF_GF_COEF_C1=0, .MSF_GF_COEF_C2=8, .MSF_GF_COEF_C3=0, .MSF_GF_COEF_C4=252}},
        .bd7       ={.bits ={.MSF_BD_THD0_L_Y=0, .MSF_BD_THD0_H_Y=32, .MSF_BD_THD1_L_Y=8, .MSF_BD_THD1_H_Y=48}},
        .bd8       ={.bits ={.MSF_BD_THD0_L_UV=0, .MSF_BD_THD0_H_UV=32, .MSF_BD_THD1_L_UV=8, .MSF_BD_THD1_H_UV=48}},
        .ab1       ={.bits ={.MSF_AB_THD_MAX=24, .MSF_AB_GF_MIN=0, .MSF_AB_NES_EN=0, .MSF_AB_NES_RATE=16, .rsv_25=0}},
        .ab2       ={.bits ={.MSF_AB_NES_MAX=8, .rsv_8=0}},
        .lc1       ={.bits ={.MSF_LC_THD_MAX0=0, .MSF_LC_THD_MAX1=2, .MSF_LC_THD_MAX2=4, .MSF_LC_THD_MAX3=2, .MSF_LC_THD_MAX4=0, .MSF_LC_THD_LUM0=0, .rsv_30=0}},
        .lc2       ={.bits ={.MSF_LC_THD_LUM1=8, .MSF_LC_THD_LUM2=16, .MSF_LC_THD_LUM3=24, .MSF_LC_THD_LUM4=31, .rsv_20=0}},
        .sl3       ={.bits ={.MSF_SL_THD_MAX0=0, .MSF_SL_THD_MAX1=1, .MSF_SL_THD_MAX2=2, .MSF_SL_THD_MAX3=3, .MSF_SL_THD_MAX4=4, .rsv_25=0}},
        .nes1      ={.bits ={.MSF_NES_COUNT_MAX=65535, .MSF_NES_COUNT_MIN=10, .rsv_24=0}},
        .nes2      ={.bits ={.MSF_NES_STAT_THD=1014, .MSF_NES_SHIFT=0, .rsv_14=0}},
        .bp        ={.bits ={.MSF_BP_THD_RATE=0, .MSF_BP_DIFF_THD0=5, .MSF_BP_DIFF_THD1=69, .rsv_22=0}},
        .vb        ={.bits ={.MSF_VB_RATE_INC=0, .rsv_5=0}},
        .nlm1      ={.bits ={.MSF_NLM_ALPHA_THD=0, .MSF_NLM_ALPHA_MAX=256, .MSF_NLM_ES_SCALE=0, .MSF_NLM_STD_RATE=10, .rsv_26=0}},
        .nlm2      ={.bits ={.MSF_NLM_EDGE_THD=64, .MSF_NLM_STD_THD0=3, .MSF_NLM_STD_THD1=80, .MSF_MSF_NLM_STD_DEF0=20, .rsv_30=0}},
        .nlm3      ={.bits ={.MSF_NLM_STD_DEF1=20, .MSF_NLM_STD_DEF2=25, .MSF_NLM_STD_DEF3=30, .MSF_NLM_STD_DEF4=35, .MSF_NLM_STD_DEF5=35, .rsv_30=0}},
        .alpha1    ={.bits ={.MSF_ALPHA_MAX_Y=1024, .MSF_ALPHA_MIN_Y=0, .MSF_ALPHA_RATE_Y0=32, .rsv_28=0}},
        .alpha2    ={.bits ={.MSF_ALPHA_RATE_Y1=32, .MSF_ALPHA_RATE_Y2=32, .MSF_ALPHA_RATE_Y3=32, .MSF_ALPHA_RATE_Y4=32, .MSF_ALPHA_RATE_Y5=32, .rsv_30=0}},
        .alpha3    ={.bits ={.MSF_ALPHA_MAX_UV=1024, .MSF_ALPHA_MIN_UV=0, .MSF_ALPHA_RATE_UV0=32, .rsv_28=0}},
        .alpha4    ={.bits ={.MSF_ALPHA_RATE_UV1=32, .MSF_ALPHA_RATE_UV2=32, .MSF_ALPHA_RATE_UV3=32, .MSF_ALPHA_RATE_UV4=32, .MSF_ALPHA_RATE_UV5=32, .MFB_D1A_MSF_ALPHA_ONE_EN=0, .rsv_31=0}},
        .hfe1      ={.bits ={.MSF_HFE_UV_RATE=12, .MSF_HFE_EDGE_WT0=63, .MSF_HFE_EDGE_WT1=42, .MSF_HFE_EDGE_WT2=21, .MSF_HFE_EDGE_WT3=0, .rsv_28=0}},
        .hfe2      ={.bits ={.MSF_HFE_EDGE_WT4=0, .MSF_HFE_NES_EN=0, .MSF_HFE_NES_RATE=32, .MSF_MSF_HFE_RATE0=0, .MSF_MSF_HFE_NES_MAX0=56, .rsv_31=0}},
        .hfe3      ={.bits ={.MSF_MSF_HFE_NES_RANGE0=80, .MSF_MSF_HFE_NES_THD0=0, .MSF_HFE_RATE1=6, .MSF_HFE_NES_MAX1=56}},
        .hfe4      ={.bits ={.MSF_HFE_NES_RANGE1=80, .MSF_HFE_NES_THD1=0, .MSF_HFE_RATE2=3, .MSF_HFE_NES_MAX2=56}},
        .hfe5      ={.bits ={.MSF_HFE_NES_RANGE2=80, .MSF_HFE_NES_THD2=0, .MSF_HFE_RATE3=2, .MSF_HFE_NES_MAX3=56}},
        .hfe6      ={.bits ={.MSF_HFE_NES_RANGE3=80, .MSF_HFE_NES_THD3=0, .MSF_HFE_RATE4=1, .MSF_HFE_NES_MAX4=56}},
        .hfe7      ={.bits ={.MSF_HFE_NES_RANGE4=80, .MSF_HFE_NES_THD4=0, .MSF_HFE_RATE5=0, .MSF_HFE_NES_MAX5=56}},
        .hfe8      ={.bits ={.MSF_HFE_NES_RANGE5=80, .MSF_HFE_NES_THD5=0, .rsv_16=0}},
        .accu      ={.bits ={.MSF_CM_ACCU_THD=0, .rsv_8=0}},
        .edge1     ={.bits ={.MSF_EC_MASK_Y_SIZE=2, .MSF_EC_MASK_UV_SIZE=1, .MSF_EC_UV_RATE=32, .MSF_EC_DOWN_RATE=1, .MSF_EC_LIMIT_RATE=32, .MSF_EC_PRE_WEIGHT=8, .MSF_EC_CUR_WEIGHT=8, .rsv_31=0}},
        .edge2     ={.bits ={.MSF_ES_MASK_Y_SIZE=2, .MSF_ES_MASK_UV_SIZE=1, .MSF_ES_UV_RATE=32, .MSF_ES_DOWN_RATE=1, .MSF_ES_LIMIT_RATE=16, .MSF_ES_PRE_WEIGHT=8, .MSF_ES_CUR_WEIGHT=0, .rsv_31=0}},
        .edge3     ={.bits ={.MSF_EE_MASK_Y_SIZE=2, .MSF_EE_MASK_UV_SIZE=1, .MSF_EE_UV_RATE=32, .MSF_EE_DOWN_RATE=1, .MSF_EE_LIMIT_RATE=32, .MSF_EE_PRE_WEIGHT=8, .MSF_EE_CUR_WEIGHT=0, .rsv_31=0}},
};

